### Test: create invite link and send email
POST http://localhost:8080/invite
Content-Type: application/json

{
  "email": "xdnjs77777@gmail.com",
  "name": "Test User",
  "role": "USER",
  "companyId": 21,
  "invitedById": "c3a4284b-5b95-4cef-84fe-c218aed3de77",
  "expiresInDays": 7
}

### Test: invite admin
POST http://localhost:8080/invite
Content-Type: application/json

{
  "email": "xdnjs77777@gmail.com",
  "name": "Test Admin",
  "role": "ADMIN",
  "companyId": 21,
  "invitedById": "c3a4284b-5b95-4cef-84fe-c218aed3de77",
  "expiresInDays": 7
}

### Test: get invite info (replace with a real invite ID)
GET http://localhost:8080/invite/3d794f55-7e92-433d-bff9-9efe72dafb28

### Test: sign up via invite (replace with a real invite ID)
POST http://localhost:8080/auth/signup/3d794f55-7e92-433d-bff9-9efe72dafb28
Content-Type: application/json

{
  "password": "newuserpass123",
  "confirmPassword": "newuserpass123"
} 
