@BASE_URL=http://localhost:8080
@accessToken=REPLACE_WITH_ACCESS_TOKEN
@userOrderId=REPLACE_WITH_USER_ORDER_UUID
@adminOrderIdPending=REPLACE_WITH_PENDING_ORDER_UUID
@adminOrderIdApproved=REPLACE_WITH_APPROVED_ORDER_UUID

### Create purchase request
POST {{BASE_URL}}/orders
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "cartItemIds": [1,2],
  "adminMessage": "Message for admin",
  "requestMessage": "Request message"
}

### Get my purchase request list
GET {{BASE_URL}}/orders
Cookie: accessToken={{accessToken}}

### Get purchase request details
GET {{BASE_URL}}/orders/{{userOrderId}}
Cookie: accessToken={{accessToken}}

### Cancel purchase request
PATCH {{BASE_URL}}/orders/{{userOrderId}}
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "status": "CANCELED"
}

### Instant purchase (admin only)
POST {{BASE_URL}}/admin/orders/instant
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "cartItemIds": [1, 2, 3]
}

### Admin - get order history (pending)
GET {{BASE_URL}}/admin/orders?status=pending&page=1&limit=4&orderBy=latest
Cookie: accessToken={{accessToken}}

### Admin - get order history (approved)
GET {{BASE_URL}}/admin/orders?status=approved&page=1&limit=4&orderBy=latest
Cookie: accessToken={{accessToken}}

### Admin - get order details (pending)
GET {{BASE_URL}}/admin/orders/{{adminOrderIdPending}}?status=pending
Cookie: accessToken={{accessToken}}

### Admin - get order details (approved)
GET {{BASE_URL}}/admin/orders/{{adminOrderIdApproved}}?status=approved
Cookie: accessToken={{accessToken}}

### Admin - approve/reject order
PATCH {{BASE_URL}}/admin/orders/{{adminOrderIdPending}}
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "status": "APPROVED",
  "adminMessage": "Approved."
} 
