name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Load GitHub repository
        uses: actions/checkout@v4

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build project
        run: npm run build

      - name: Compress build file
        run: tar -czvf project.tar.gz dist .env package.json package-lock.json

      - name: Transfer build file to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.tar.gz
          target: /home/ec2-user/6-Snack-BE

      - name: SSH and Restart Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ec2-user/6-Snack-BE
            tar -xvf project.tar.gz
            rm -rf project.tar.gz
            npm ci --production
            npx prisma migrate deploy
            pm2 delete "backend-server" || true
            pm2 start dist/server.js --name "backend-server"